### ISSUE TITLE
Upgrade  react-scripts-ts    2.5.0  →     2.8.0 bug

### ISSUE THREAD

**Issue by virzak** [comerc/cra-ts-antd#3]
As soon as react-scripts-ts  is upgraded, it all stops working

```
C:\Code\Sandbox\cra-ts-antd\config-overrides.js:5
  tsLoader.loader = require.resolve('awesome-typescript-loader')
                  ^

TypeError: Cannot set property 'loader' of undefined
    at Object.override [as webpack] (C:\Code\Sandbox\cra-ts-antd\config-overrides.js:5:19)
    at Object.<anonymous> (C:\Code\Sandbox\cra-ts-antd\node_modules\react-app-rewired\scripts\start.js:13:13)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cra-ts-antd@0.1.0 start: `react-app-rewired start --scripts-version react-scripts-ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cra-ts-antd@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\virzak\AppData\Roaming\npm-cache\_logs\2017-12-16T20_16_53_527Z-debug.log
```

**Comment by comerc** [comment]
Thanks! Fixed.

**Comment by virzak** [comment]
Красава!
